- name: Backup file config neutron.conf
  copy:
   src: /etc/neutron/neutron.conf
   dest: /etc/neutron/neutron.conf.bak
   remote_src: yes

- name: Backup file config ml2_conf.ini
  copy: 
   src: /etc/neutron/plugins/ml2/ml2_conf.ini
   dest: /etc/neutron/plugins/ml2/ml2_conf.ini.bak
   remote_src: yes

- name: Backup file openvswitch_agent.ini
  copy:
   src: /etc/neutron/plugins/ml2/openvswitch_agent.ini
   dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini.bak
   remote_src: yes

- name: Backup file config l3_agent.ini
  copy: 
   src: /etc/neutron/l3_agent.ini
   dest: /etc/neutron/l3_agent.ini.bak
   remote_src: yes

- name: Backup file config dhcp_agent.ini
  copy: 
   src: /etc/neutron/dhcp_agent.ini
   dest: /etc/neutron/dhcp_agent.ini.bak
   remote_src: yes

- name:  Backup file config metadata_agent.ini
  copy: 
   src: /etc/neutron/metadata_agent.ini
   dest: /etc/neutron/metadata_agent.ini.bak
   remote_src: yes

- name: Config neutron server
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    mode: '0660'

- name: Config Modular Layer 2 (ML2) plug-in
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    mode: '0660'

- name: Config the Open vSwitch agent
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    mode: '0660'

- name: Configure the L3 agent
  template: 
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    mode: '0660'

- name: Configure the DHCP agent
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
    mode: '0660'

- name: Configure the metadata agent
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
    mode: '0660'

- name: link file ml2 config
  shell:  ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini

