---
- name: Install the components for Neutron
  yum:
    name: "{{ item }}"
  with_items: 
    - 'openstack-neutron'
    - 'openstack-neutron-ml2'
    - 'openstack-neutron-openvswitch'
    - 'ebtables'
    - 'libibverbs'
