---
- name: Backup file config horizon
  copy:
   src: /etc/openstack-dashboard/local_settings
   dest: /etc/openstack-dashboard/local_settings.bak
   remote_src: yes

- name: Edit the /etc/openstack-dashboard/local_settings file
  template:
    src: local_settings.j2
    dest: /etc/openstack-dashboard/local_settings

- name: Config file /etc/httpd/conf.d/openstack-dashboard.conf
  lineinfile:
    path: /etc/httpd/conf.d/openstack-dashboard.conf
    line: WSGIApplicationGroup %{GLOBAL}


- name: Restart HTTPD
  systemd:
    state : restarted
    enabled: true
    name: httpd.service

- name: Restart memcached
  systemd:
    state : restarted
    enabled: true
    name: memcached.service


