---
- name: Backup file config glance-api.conf
  copy:
   src: /etc/glance/glance-api.conf
   dest: /etc/glance/glance-api.conf.bak
   remote_src: yes

- name: Config file glance-api.conf
  template:
    src: glance-api.conf.j2
    dest: /etc/glance/glance-api.conf


