---
- name: Check /etc/glance/glance-api.conf.bak existed
  stat:
    path: /etc/glance/glance-api.conf.bak
  register: glance_api_conf_bak

- name: Backup file config glance-api.conf
  copy:
    src: /etc/glance/glance-api.conf
    dest: /etc/glance/glance-api.conf.bak
    remote_src: yes
  when: 
    - not glance_api_conf_bak.stat.exists

- name: Config file glance-api.conf
  template:
    src: glance-api.conf.j2
    dest: /etc/glance/glance-api.conf


