---
- name: export env OPS
  shell: source /root/admin-openrc

- name: Create user Glance
  os_user:
    name: glance
    auth: "{{ openstack_auth }}"
    password: "{{ glance_pass }}"
    domain: default
  run_once: true

- name: Create role for user glance
  os_user_role:
    auth: "{{ openstack_auth }}"
    user: glance
    role: admin
    project: service
    state: present
  run_once: true

- name: Create Image service
  os_keystone_service:
    name: glance
    auth: "{{ openstack_auth }}"
    service_type: image
    description: Openstack Image
  run_once: true


- name: Create endpoint
  os_keystone_endpoint:
     auth: "{{ openstack_auth }}"
     service: glance
     endpoint_interface: "{{ item }}"
     url: http://{{ IP_VIP }}:9292
     region: "{{ REGION }}"
     state: present
  with_items:
    - public
    - admin
    - internal
  run_once: true



