---
- name: Config section placement_database
  ini_file:
    path: /etc/placement/placement.conf
    section: placement_database
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: '{{ placement_database }}'

- name: config section keystone_authtoken
  ini_file:
       path: /etc/placement/placement.conf
       section: keystone_authtoken
       option: "{{ item.key }}"
       value: "{{ item.value }}"
  with_dict: '{{ keystone_authtoken }}'

- name: config section api
  ini_file:
       path: /etc/placement/placement.conf
       section: api
       option: "{{ item.key }}"
       value: "{{ item.value }}"
  with_dict: '{{ api }}'
