---
- name: Backup file config placement.conf
  copy:
   src: /etc/placement/placement.conf
   dest: /etc/placement/placement.conf.bak
   remote_src: yes

- name: Config file placement.conf
  template:
    src: placement.conf.j2
    dest: /etc/placement/placement.conf


