---
DEFAULT:
   - my_ip: "{{ MGNT_IP }}"
   - rootwrap_config: /etc/nova/rootwrap.conf
   - enabled_apis: osapi_compute,metadata
   - osapi_compute_listen: "{{ MGNT_IP }}"
   - osapi_compute_listen_port: 8774
   - metadata_host: "{{ MGNT_IP }}"
   - metadata_listen: "{{ MGNT_IP }}"
   - metadata_listen_port: 8775
   - transport_url: "rabbit://{%- for item in groups['controller'] %}openstack:{{ rabbitmq_pass }}@{{  hostvars[item].ansible_default_ipv4.address }}:5672{% if not loop.last %},{% endif %}{% endfor %}"
   - use_neutron: true
   - firewall_driver: nova.virt.firewall.NoopFirewallDriver

api:
   - auth_strategy: keystone

api_database: 
   - connection: mysql+pymysql://nova:{{ novadb_pass }}@{{ IP_VIP }}/nova_api

database:
   - connection: mysql+pymysql://nova:{{ novadb_pass }}@{{ IP_VIP }}/nova

cache:
   - memcache_servers: "{%- for item in groups['controller'] %}{{  hostvars[item].ansible_default_ipv4.address }}:11211{% if not loop.last %},{% endif %}{% endfor %}"
   - enabled: true
   - backend: oslo_cache.memcache_pool

oslo_messaging_notifications: 
   - transport_url: "rabbit://{%- for item in groups['controller'] %}openstack:{{ rabbitmq_pass }}@{{  hostvars[item].ansible_default_ipv4.address }}:5672{% if not loop.last %},{% endif %}{% endfor %}"


keystone_authtoken:
   - www_authenticate_uri: http://{{ IP_VIP }}:5000/
   - auth_url: http://{{ IP_VIP }}:5000/
   - memcached_servers: "{%- for item in groups['controller'] %}{{  hostvars[item].ansible_default_ipv4.address }}:11211{% if not loop.last %},{% endif %}{% endfor %}"
   - auth_type: password
   - project_domain_name: Default
   - user_domain_name: Default
   - project_name: service
   - username: nova
   - password: "{{ nova_pass }}"


vnc:
   - enabled: true
   - novncproxy_host: "{{ MGNT_IP }}"
   - novncproxy_port: 6080
   - server_listen: "{{ MGNT_IP }}"
   - novncproxy_base_url: http://{{ IP_VIP }}:6080/vnc_auto.html
   - server_proxyclient_address: "{{ MGNT_IP }}"

glance:
   - api_servers: http://{{ IP_VIP }}:9292

oslo_concurrency:
   - lock_path: /var/lib/nova/tmp

placement:
   - os_region_name: "{{ REGION }}"
   - project_domain_name: Default
   - project_name: service
   - auth_type: password
   - user_domain_name: Default
   - auth_url: http://{{ IP_VIP }}:5000/v3
   - username: placement
   - password: "{{ placement_pass }}"

cinder:
   - os_region_name: "{{ REGION }}"

neutron: 
   - url: http://{{ IP_VIP }}:9696
   - auth_url: http://{{ IP_VIP }}:5000
   - auth_type: password
   - project_domain_name: Default
   - user_domain_name: Default
   - region_name: "{{ REGION }}"
   - project_name: service
   - username: neutron
   - password: "{{ neutron_pass }}"
   - service_metadata_proxy: true
   - metadata_proxy_shared_secret: "{{ metadata_secret }}"

