---
- name: Backup file config nova.conf
  copy:
   src: /etc/nova/nova.conf
   dest: /etc/nova/nova.conf.bak
   remote_src: yes

- name: Config file nova.conf
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf


