---
- name: Create user Nova
  os_user:
    name: nova
    auth: "{{ openstack_auth }}"
    password: "{{ nova_pass }}"
    domain: default
  run_once: true

- name: Create role for user Nova
  os_user_role:
    auth: "{{ openstack_auth }}"
    user: nova
    role: admin
    project: service
    state: present
  run_once: true

- name: Create Compute service
  os_keystone_service:
    name: nova
    auth: "{{ openstack_auth }}"
    service_type: compute
    description: Openstack Compute
  run_once: true

- name: Create endpoint for Nova
  os_keystone_endpoint:
     auth: "{{ openstack_auth }}"
     service: nova
     endpoint_interface: "{{ item }}"
     url: http://{{ IP_VIP }}:8774/v2.1
     region: "{{ REGION }}"
     state: present
  with_items:
    - public
    - admin
    - internal
  run_once: true

