---
- name: Backup file config keystone.conf
  copy:
   src: /etc/keystone/keystone.conf
   dest: /etc/keystone/keystone.conf.bak
   remote_src: yes

- name: Config file keystone.conf
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf

